apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: b4nbce9pu-nodejs-gitops
  description: This is GitOps manifest for b4nbce9pu-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=b4nbce9pu-nodejs
    backstage.io/kubernetes-id: b4nbce9pu-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: b4nbce9pu-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:b4nbce9pu-nodejs
